using System.Xml.Linq;
using StationeersModCreator.Core.Models;
using StationeersModCreator.Core.Services;
namespace StationeersModCreator.Checks;

public sealed class InventoryCheckRunner
{
    readonly JsonNativeCatalogRepository _native; readonly JsonInventoryCatalog _inventory; readonly InventoryResolver _resolver; readonly InventoryLayoutService _layout; readonly ProjectValidator _validator; readonly JsonCatalogRepository _catalog;
    public InventoryCheckRunner(string content) { _native = new(Path.Combine(content, "native-catalog.json")); _inventory = new(Path.Combine(content, "inventory-catalog.json")); _resolver = new(_native); _layout = new(_inventory); _catalog = new(Path.Combine(content, "catalog.json")); _validator = new(_catalog, new NumericValueValidator(), new NativeDefinitionValidator(_native, _catalog)); }
    static void Require(bool condition, string message) { if (!condition) throw new InvalidOperationException(message); }
    public void Run()
    {
        var project = new ModProject { CatalogFingerprint = _catalog.Fingerprint }; var source = _native.Resolve("StartCondition", "DefaultStart"); var compiler = new InventoryModCompiler(_native, _layout, _resolver);
        Require(_inventory.Prefabs.Count == 1567, "Inventory catalog count changed."); Require(_layout.Slots("Character", "Human").Count == 11, "Character slot count."); Require(_layout.Slots("Character", "Robot").Single(x => x.Index == 6).TypeName == "Battery", "Robot battery mapping.");
        foreach (var species in new[] { "Human", "Zrilian", "Robot" }) foreach (var difficulty in new[] { "Creative", "Easy", "Normal", "Stationeer" }) foreach (var evt in new[] { "NewPlayerKit", "RespawnPlayerKit" }) { var context = new InventoryContext("DefaultStart", evt, species, difficulty); var resolved = _resolver.Resolve(context, project); var layout = _layout.Layout(resolved.Xml, species); Require(layout.Diagnostics.Count == 0, string.Join(";", layout.Diagnostics)); if (species == "Robot") Require(layout.Placements.Any(x => x.ParentPath == "" && x.SlotIndex == 6), "Robot kit battery absent."); if (species == "Human" && evt == "RespawnPlayerKit" && difficulty is "Normal" or "Stationeer") Require(layout.Placements.Any(x => x.PrefabName.Contains("Emergency")), "Emergency respawn branch absent."); }
        Console.WriteLine("PASS: 24 species/difficulty/event contexts resolve into compatible nested slots.");
        var selected = new InventoryContext("DefaultStart", "NewPlayerKit", "Human", "Normal"); var preview = XElement.Parse(_resolver.Resolve(selected, project).Xml); var duct = preview.Elements("Item").Single(x => (string?)x.Attribute("Id") == "ItemDuctTape"); duct.Remove(); var changes = compiler.Compile(new(selected, "Forge.InventoryTest", source.Key, source.SourceHash, preview.ToString()), project); Require(changes.Count == 3 && changes.All(x => x.IsAddition), "Kit export is not three local additions."); project.Definitions.AddRange(changes); _validator.Validate(project, false);
        foreach (var species in new[] { "Human", "Zrilian", "Robot" }) foreach (var difficulty in new[] { "Creative", "Easy", "Normal", "Stationeer" }) { var context = selected with { Species = species, Difficulty = difficulty }; var before = XElement.Parse(_resolver.Resolve(context, new()).Xml); var after = XElement.Parse(_resolver.Resolve(context with { StartId = "Forge.InventoryTest" }, project).Xml); if (species == "Human" && difficulty == "Normal") before.Elements("Item").Single(x => (string?)x.Attribute("Id") == "ItemDuctTape").Remove(); Require(XNode.DeepEquals(before, after), "Unselected context changed: " + species + " " + difficulty); }
        var other = selected with { Event = "RespawnPlayerKit", Species = "Zrilian", Difficulty = "Easy" }; var second = XElement.Parse(_resolver.Resolve(other with { StartId = "Forge.InventoryTest" }, project).Xml); second.Elements("Item").First().Remove(); foreach (var change in compiler.Compile(new(other, "Forge.InventoryTest", source.Key, source.SourceHash, second.ToString()), project)) { project.Definitions.RemoveAll(x => x.ExportId == change.ExportId); project.Definitions.Add(change); }
        _validator.Validate(project, false); Require(!XElement.Parse(_resolver.Resolve(selected with { StartId = "Forge.InventoryTest" }, project).Xml).Elements("Item").Any(x => (string?)x.Attribute("Id") == "ItemDuctTape"), "Second event edit reverted first.");
        Console.WriteLine("PASS: additive kit/router/start exports preserve all other contexts and repeated edits.");
        Require(_layout.Layout("<Spawn><Item Id='ItemDuctTape' SlotIndex='1'/><Item Id='ItemDuctTape' SlotIndex='1'/></Spawn>", "Human").Diagnostics.Count == 1, "Occupied slot accepted."); Require(_layout.Layout("<Spawn><Item Id='ItemDuctTape' SlotIndex='3'/></Spawn>", "Human").Diagnostics.Count == 1, "Incompatible slot accepted."); Require(_layout.Layout("<Spawn><Item Id='ItemDuctTape' SlotId='RightHand'/></Spawn>", "Human").Placements.Single().SlotIndex == 1, "Slot key hash mapping failed."); Console.WriteLine("PASS: occupied slots, incompatible types and slot ID hashes.");
    }
}
