using System.Xml.Linq;
using StationeersModCreator.Core.Models;
using StationeersModCreator.Core.Interfaces;
namespace StationeersModCreator.Core.Services;

public sealed class InventoryLayoutService : IInventoryLayoutService
{
    private readonly IInventoryCatalog _catalog;
    public InventoryLayoutService(IInventoryCatalog catalog) { _catalog = catalog; }
    public IReadOnlyList<InventorySlotDefinition> Slots(string prefab, string species) => _catalog.Find(prefab).Slots.Select(s => prefab == "Character" && species == "Robot" && s.Key == "Uniform" ? s with { Key = "Battery", StringHash = SlotKeyHash.Hash("Battery"), Type = 14, TypeName = "Battery" } : s).ToList();
    public bool Fits(InventorySlotDefinition slot, string prefab) { var item = _catalog.Find(prefab); return (slot.Type == 0 || slot.Type == item.SlotType) && (slot.SpecificPrefabHashes.Length == 0 || slot.SpecificPrefabHashes.Contains(item.PrefabHash)); }
    public InventoryLayout Layout(string xml, string species) { var editor = new XmlDefinitionEditor(xml); var placements = new List<InventoryPlacement>(); var errors = new List<string>(); Assign(editor, "", "Character", species, placements, errors); return new(placements, errors); }
    private void Assign(XmlDefinitionEditor editor, string parentPath, string parentPrefab, string species, List<InventoryPlacement> placements, List<string> errors) { IReadOnlyList<InventorySlotDefinition> slots; try { slots = Slots(parentPrefab, species); } catch (InvalidDataException e) { errors.Add(e.Message); return; } var occupied = new HashSet<int>(); var parent = editor.Node(parentPath); var groups = parent.Name == "Spawn" ? new[] { "Item", "DynamicThing" } : new[] { "DynamicThing", "Item" }; foreach (var tag in groups) foreach (var item in parent.Elements(tag)) { var id = (string?)item.Attribute("Id") ?? ""; var path = editor.ChildPath(parentPath, item); try { var prefab = _catalog.Find(id); InventorySlotDefinition? slot = null; if (item.Attribute("SlotIndex") is { } attr) { if (!int.TryParse(attr.Value, out var index) || index < 0) throw new InvalidDataException("Invalid slot index."); slot = slots.FirstOrDefault(x => x.Index == index); } else if (item.Attribute("SlotId") is { } key) slot = slots.FirstOrDefault(x => !occupied.Contains(x.Index) && x.StringHash == SlotKeyHash.Hash(key.Value)); else if (item.Attribute("SlotClass") is { } type) slot = slots.FirstOrDefault(x => !occupied.Contains(x.Index) && x.TypeName == type.Value); else slot = slots.FirstOrDefault(x => !occupied.Contains(x.Index) && Fits(x, id)); if (slot is null) throw new InvalidDataException("No available slot for " + id + " in " + parentPrefab); if (!occupied.Add(slot.Index)) throw new InvalidDataException("Slot " + slot.Index + " is occupied in " + parentPrefab); if (!Fits(slot, id)) throw new InvalidDataException("Incompatible " + id + " for " + parentPrefab + " slot " + slot.Index); placements.Add(new(parentPath, slot.Index, path, id)); Assign(editor, path, id, species, placements, errors); } catch (InvalidDataException e) { errors.Add(path + ": " + e.Message); } } }
}
