using System.Collections.ObjectModel;
using System.Xml.Linq;
using StationeersModCreator.Core.Interfaces;
using StationeersModCreator.Core.Models;
using StationeersModCreator.Core.Services;
using StationeersModCreator.Desktop.Interfaces;
namespace StationeersModCreator.Desktop.ViewModels;

public sealed class InventoryEditorViewModel : ObservableViewModel
{
    private readonly INativeCatalogRepository _native; private readonly IInventoryCatalog _catalog; private readonly IInventoryResolver _resolver; private readonly IInventoryLayoutService _layout; private readonly IInventoryModCompiler _compiler; private readonly IDraftService _draft; private readonly IBitmapProvider _images; private readonly Action _changed;
    private string _start = "DefaultStart", _event = "NewPlayerKit", _species = "Human", _difficulty = "Normal", _export = "Forge.MyStart", _path = "", _status = "Choose a context and open its inventory.", _item = "", _quantity = "1", _charge = "Full", _gas = "Oxygen", _moles = "150", _celsius = "20"; private bool _pending; private XmlDefinitionEditor? _xml; private NativeDefinition? _source; private InventorySlotCardViewModel? _selected; private InventoryDestinationViewModel? _destination;
    public ObservableCollection<InventorySlotCardViewModel> Slots { get; } = []; public ObservableCollection<NativeFieldEditorViewModel> Fields { get; } = []; public ObservableCollection<string> Diagnostics { get; } = []; public ObservableCollection<string> ItemIds { get; } = []; public ObservableCollection<InventoryDestinationViewModel> Destinations { get; } = [];
    public IReadOnlyList<string> Starts => _native.Definitions.Where(x => x.Tag == "StartCondition").Select(x => x.Id).Distinct().Order().ToList(); public string[] Events { get; } = ["NewPlayerKit", "RespawnPlayerKit"]; public string[] Species { get; } = ["Human", "Zrilian", "Robot"]; public IReadOnlyList<string> Difficulties => _native.Definitions.Where(x => x.Tag == "DifficultySetting").Select(x => x.Id).Distinct().ToList(); public string[] ChargeStates { get; } = ["Full", "Empty"]; public IReadOnlyList<string> GasTypes => _native.Definitions.SelectMany(x => XElement.Parse(x.Xml).Descendants("Gas")).Select(x => (string?)x.Attribute("Type")).OfType<string>().Distinct().Order().ToList();
    public string StartId { get => _start; set => Set(ref _start, value); }
    public string Event { get => _event; set => Set(ref _event, value); }
    public string SpeciesName { get => _species; set => Set(ref _species, value); }
    public string Difficulty { get => _difficulty; set => Set(ref _difficulty, value); }
    public string ExportStartId { get => _export; set { if (Set(ref _export, value) && _xml is not null) { _pending = true; _changed(); } } }
    public string ItemId { get => _item; set => Set(ref _item, value); }
    public string Quantity { get => _quantity; set => Set(ref _quantity, value); }
    public string Charge { get => _charge; set => Set(ref _charge, value); }
    public string GasType { get => _gas; set => Set(ref _gas, value); }
    public string GasMoles { get => _moles; set => Set(ref _moles, value); }
    public string GasCelsius { get => _celsius; set => Set(ref _celsius, value); }
    public InventoryDestinationViewModel? Destination { get => _destination; set => Set(ref _destination, value); }
    public string Status { get => _status; private set => Set(ref _status, value); }
    public string Breadcrumb => _xml is null ? "Load an inventory" : _path.Length == 0 ? $"{_loadedContext!.Species} / {_loadedContext.Event} / {_loadedContext.Difficulty}" : _path; public string SelectedName => _selected?.Caption ?? "Select an equipment or inventory slot"; public string SelectedSlot => _selected is null ? "" : $"Slot {_selected.Slot.Index} · {_selected.Slot.TypeName}"; public bool HasItem => _selected?.HasItem == true; public bool CanOpen => HasItem && _catalog.Find(_selected!.PrefabName!).Slots.Count > 0; public bool CanEditSlot => _selected is not null && !_selected.IsSpeciesManaged; public bool HasPendingEdits => _pending; public string Summary => $"{Slots.Count(x => x.HasItem)} occupied / {Slots.Count(x => !x.IsSpeciesManaged)} inventory slots";
    private InventoryContext? _loadedContext;
    public RelayCommand LoadCommand { get; }
    public RelayCommand RootCommand { get; }
    public RelayCommand ParentCommand { get; }
    public RelayCommand OpenContentsCommand { get; }
    public RelayCommand AddCommand { get; }
    public RelayCommand RemoveCommand { get; }
    public RelayCommand MoveCommand { get; }
    public RelayCommand ApplyQuantityCommand { get; }
    public RelayCommand ApplyChargeCommand { get; }
    public RelayCommand AddGasCommand { get; }
    public RelayCommand StageCommand { get; }
    public RelayCommand RestoreCommand { get; }
    public InventoryEditorViewModel(INativeCatalogRepository native, IInventoryCatalog catalog, IInventoryResolver resolver, IInventoryLayoutService layout, IInventoryModCompiler compiler, IDraftService draft, IBitmapProvider images, Action changed) { _native = native; _catalog = catalog; _resolver = resolver; _layout = layout; _compiler = compiler; _draft = draft; _images = images; _changed = changed; LoadCommand = new(() => Run(Load)); RootCommand = new(() => Open("")); ParentCommand = new(() => Open(ParentPath(_path))); OpenContentsCommand = new(() => { if (CanOpen) Open(_selected!.ItemPath!); }); AddCommand = new(() => Run(Add)); RemoveCommand = new(() => Run(Remove)); MoveCommand = new(() => Run(Move)); ApplyQuantityCommand = new(() => Run(ApplyQuantity)); ApplyChargeCommand = new(() => Run(ApplyCharge)); AddGasCommand = new(() => Run(AddGas)); StageCommand = new(() => Run(Stage)); RestoreCommand = new(() => { _pending = false; _draft.Project.PendingInventory = null; Run(Load); }); Load(); }
    private static string ParentPath(string path) { var i = path.LastIndexOf('/'); return i < 0 ? "" : path[..i]; }
    private void Run(Action action) { try { action(); } catch (Exception e) { Status = e.Message; } }
    private void Load() { if (_pending) throw new InvalidDataException("Stage or restore the current kit before loading another context."); var context = new InventoryContext(StartId, Event, SpeciesName, Difficulty); var source = _native.Resolve("StartCondition", StartId); var effective = _draft.Project.Definitions.Any(x => x.ExportId == ExportStartId) ? context with { StartId = ExportStartId } : context; var resolved = _resolver.Resolve(effective, _draft.Project); var xml = new XmlDefinitionEditor(resolved.Xml); _source = source; _loadedContext = context; _xml = xml; _path = ""; Open(""); Status = "Loaded " + SpeciesName + " " + Difficulty + " · " + Event + ". Sources: " + string.Join(", ", resolved.Sources); }
    public void Open(string path) { if (_xml is null) return; _path = path; _selected = null; Fields.Clear(); var prefab = path.Length == 0 ? "Character" : (string?)_xml.Node(path).Attribute("Id") ?? ""; var result = _layout.Layout(_xml.Xml, _loadedContext!.Species); Slots.Clear(); foreach (var slot in _layout.Slots(prefab, _loadedContext.Species)) { var item = result.Placements.FirstOrDefault(x => x.ParentPath == path && x.SlotIndex == slot.Index); var detail = item is null ? slot.TypeName : ItemDetail(_xml.Node(item.ItemPath)); Slots.Add(new(slot, path, item, _images, Select, detail)); } Diagnostics.Clear(); foreach (var error in result.Diagnostics) Diagnostics.Add(error); NotifyAll(); }
    private static string ItemDetail(XElement item) { var quantity = (string?)item.Element("Quantity")?.Attribute("Value"); var charge = (string?)item.Element("Charge")?.Attribute("State"); return (quantity is null ? "" : "× " + quantity + "  ") + (charge is null ? "" : "Charge " + charge + "  ") + (item.Elements("Item").Count() + item.Elements("DynamicThing").Count() > 0 ? "Contains inventory" : ""); }
    private void Select(InventorySlotCardViewModel slot) { _selected = slot; Fields.Clear(); if (slot.ItemPath is not null) foreach (var field in _xml!.Fields(slot.ItemPath).Where(x => !x.Path.EndsWith("/@Id", StringComparison.Ordinal))) Fields.Add(new(field, (path, value) => { _xml.Set(path, value); Dirty(); })); ItemIds.Clear(); if (!slot.IsSpeciesManaged) foreach (var p in _catalog.Prefabs.Where(x => _layout.Fits(slot.Slot, x.Name)).OrderBy(x => x.Name)) ItemIds.Add(p.Name); ItemId = ItemIds.FirstOrDefault() ?? ""; Destinations.Clear(); if (slot.PrefabName is not null) { var layout = _layout.Layout(_xml!.Xml, _loadedContext!.Species); foreach (var parent in _xml.Root.DescendantsAndSelf().Where(x => x == _xml.Root || x.Name == "Item" || x.Name == "DynamicThing")) { var path = NodePath(parent); if (path == slot.ItemPath || path.StartsWith(slot.ItemPath + "/", StringComparison.Ordinal)) continue; var prefab = parent == _xml.Root ? "Character" : (string?)parent.Attribute("Id") ?? ""; foreach (var target in _layout.Slots(prefab, _loadedContext.Species).Where(x => x.TypeName != "Organ" && _layout.Fits(x, slot.PrefabName) && !layout.Placements.Any(p => p.ParentPath == path && p.SlotIndex == x.Index))) Destinations.Add(new(path, target.Index, prefab + " / " + (target.Key.Length > 0 ? target.Key : target.TypeName) + " · " + target.Index)); } } Destination = Destinations.FirstOrDefault(); NotifyAll(); }
    private string NodePath(XElement node) => node == _xml!.Root ? "" : _xml.ChildPath(NodePath(node.Parent!), node);
    private void EnsureSlot() { if (_selected is null || _selected.IsSpeciesManaged) throw new InvalidDataException("Choose an editable inventory slot."); }
    private XElement EnsureItem() { EnsureSlot(); return _selected!.ItemPath is null ? throw new InvalidDataException("This slot is empty.") : _xml!.Node(_selected.ItemPath); }
    private void Add() { EnsureSlot(); if (_selected!.HasItem) throw new InvalidDataException("Remove or move this item before adding another."); if (!_layout.Fits(_selected.Slot, ItemId)) throw new InvalidDataException("This item is incompatible with the selected slot."); var item = new XElement("Item", new XAttribute("Id", ItemId), new XAttribute("SlotIndex", _selected.Slot.Index)); if (Quantity != "1") item.Add(new XElement("Quantity", new XAttribute("Value", Quantity))); _xml!.Node(_path).Add(item); Dirty(); Open(_path); }
    private void Remove() { EnsureItem().Remove(); Dirty(); Open(_path); }
    private void Move() { var item = EnsureItem(); var target = Destination ?? throw new InvalidDataException("Choose an empty compatible destination."); var parent = _xml!.Node(target.ParentPath); if (parent == item || parent.Ancestors().Contains(item)) throw new InvalidDataException("A container cannot enter its own hierarchy."); item.Remove(); item.Attribute("SlotId")?.Remove(); item.Attribute("SlotClass")?.Remove(); item.SetAttributeValue("SlotIndex", target.SlotIndex); parent.Add(item); Dirty(); Open(""); }
    private void ApplyQuantity() { var item = EnsureItem(); if (!decimal.TryParse(Quantity, out var q) || q < 1 || q != decimal.Truncate(q)) throw new InvalidDataException("Use a positive whole quantity."); var p = _catalog.Find((string)item.Attribute("Id")!); if (p.MaxQuantity is { } max && q > max) throw new InvalidDataException("Quantity exceeds the source stack maximum."); var element = item.Element("Quantity"); if (element is null) { element = new XElement("Quantity"); item.Add(element); } element.SetAttributeValue("Value", Quantity); Dirty(); Select(_selected!); }
    private void ApplyCharge() { var item = EnsureItem(); if (_catalog.Find((string)item.Attribute("Id")!).SlotTypeName != "Battery") throw new InvalidDataException("Choose a battery to set its charge."); var element = item.Element("Charge"); if (element is null) { element = new XElement("Charge"); item.Add(element); } element.SetAttributeValue("State", Charge); Dirty(); Select(_selected!); }
    private void AddGas() { var item = EnsureItem(); var type = _catalog.Find((string)item.Attribute("Id")!).SlotTypeName; if (type is not ("GasCanister" or "LiquidCanister" or "Portables")) throw new InvalidDataException("Choose a canister or tank to add gas data."); item.Add(new XElement("Gas", new XAttribute("Type", GasType), new XAttribute("Moles", GasMoles), new XAttribute("Celsius", GasCelsius))); Dirty(); Select(_selected!); }
    private void Dirty() { _pending = true; _changed(); Notify(nameof(HasPendingEdits)); }
    private void Stage() { if (!_pending) throw new InvalidDataException("Edit the inventory before staging a local kit."); var pending = CapturePending()!; var changes = _compiler.Compile(pending, _draft.Project); _draft.StageDefinitions(changes); _draft.Project.PendingInventory = null; _pending = false; _changed(); Open(_path); Status = "Local kit, context router and new start staged. Other species, difficulties and the arrival object retain their references."; }
    public PendingInventoryDraft? CapturePending() => _pending && _source is not null && _xml is not null ? new(_loadedContext!, ExportStartId, _source.Key, _source.SourceHash, _xml.Xml) : null;
    public void VerifyStaged() { if (_pending) throw new InvalidDataException("Stage or restore inventory edits before exporting."); }
    public void ResetProject() { _pending = false; if (_draft.Project.PendingInventory is { } p) { _source = _native.Find(p.SourceKey); _loadedContext = p.Context; _start = p.Context.StartId; _event = p.Context.Event; _species = p.Context.Species; _difficulty = p.Context.Difficulty; _export = p.ExportStartId; _xml = new(p.Xml); _pending = true; Open(""); foreach (var n in new[] { nameof(StartId), nameof(Event), nameof(SpeciesName), nameof(Difficulty), nameof(ExportStartId) }) Notify(n); } else Run(Load); }
    private void NotifyAll() { foreach (var n in new[] { nameof(Breadcrumb), nameof(SelectedName), nameof(SelectedSlot), nameof(HasItem), nameof(CanOpen), nameof(CanEditSlot), nameof(Summary) }) Notify(n); }
}
